version: '3'

services:
  app:
    build: . 
    entrypoint: .docker/entry-point.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    image: mongo:5.0.5
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - 27018:27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=analytics

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    depends_on:
      - db
  
  redis:
    image: redis:6.2.6-alpine3.14